modules:
  eye:
    class: examples.wiring_builder_demo.Eye
  lgn:
    class: examples.wiring_builder_demo.LGN
  sc:
    class: examples.wiring_builder_demo.SC

wiring:
  - from: eye.out.visual_stream
    to: [lgn.in.retina]
  - from: lgn.out.thalamus
    to: [sc.in.vision]
